Артём, третий контест, задача А, official.contest.yandex.ru/contest/11654/run-report/19428017/
starar/cpp-2018-course pull request #1
Opened 2019-03-22 11:53 UTC by starar

[https://official.contest.yandex.ru/contest/11654/run-report/19428017/]()

2019-03-28 22:49 UTC, ifsmirnov requested changes
Очень неплохо, если не считать того, что итерация происходит не строго за O(числа элементов).

2019-03-28 22:49 UTC, ifsmirnov commented on HashMap
> +    size_t Size;
Нужна консистентность в именовании. Если уж пришлось назвать Size c большой буквы, надо остальные поля так же называть.

2019-03-28 22:49 UTC, ifsmirnov commented on HashMap
> +            : hash(h), entriesCount(0), Size(DEFAULT_SIZE) {
Копирования этой строчки можно избежать с помощью delegating constructors.

2019-03-28 22:49 UTC, ifsmirnov commented on HashMap
> +        typename std::list<std::pair<const KeyType, ValueType>>::const_iterator indexInBucket;
Копипаст. Можно сделать функцию, которая возвращает index, indexInBucket, а затем создавать в begin/begin const нужный тип итератора.

2019-03-28 22:49 UTC, ifsmirnov commented on HashMap
> +        size_t index = 0;
bucketIndex лучше.

2019-03-28 22:49 UTC, ifsmirnov commented on HashMap
> +    double load_factor() {
const

2019-03-28 22:49 UTC, ifsmirnov commented on HashMap
> +    size_t valueOfSize() const {
Очень странное название. Может, capacity? Или bucketCount? В зависимости от того, что там реально лежит.

2019-03-28 22:49 UTC, ifsmirnov commented on HashMap
> +        size_t index = findIndex(key, Size);
Тоже копипаст, как и в случае с begin()/begin() const.

2019-03-29 09:23 UTC, starar commented on HashMap
> +    size_t valueOfSize() const {
> Очень неплохо, если не считать того, что итерация происходит не строго за O(числа элементов).

Всё исправил

2019-03-29 09:27 UTC, starar commented
[https://official.contest.yandex.ru/contest/11654/run-report/19809144/]() -- посылка

2019-10-20 10:59 UTC, merged